# Generated by Django 3.2.15 on 2022-08-16 18:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='country',
            field=models.CharField(default='United States', max_length=255),
        ),
        migrations.AddField(
            model_name='park',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
        migrations.AddField(
            model_name='park',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='park',
            name='street_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='park',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
