# Generated by Django 3.2.15 on 2022-08-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220816_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='street_suffix',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
