# Generated by Django 3.2.15 on 2022-08-16 19:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_park_street_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.park_image_file_path),
        ),
    ]
