# Generated by Django 3.2.15 on 2022-08-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220817_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='all_posts',
        ),
    ]
