# Generated by Django 3.2.15 on 2022-08-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_user_all_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
