# Generated by Django 3.2.15 on 2022-08-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220823_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
